### ISSUE TITLE
Add fluent-plugin-aws-elasticsearch-service plugin

### ISSUE THREAD

**Issue by hackerx15** [stevehipwell/fluentd-aggregator#2]
As the Elasticsearch plugin currently doesn't support AWS sign V4, this plugin extends from elastic search and puts a wrapper around it to authorise sending logs to AWS Elasticsearch when the access is set as restricted.

**Comment by stevehipwell** [comment]
@hackerx15 do you know if this plugin can be installed alongside `fluent-plugin-elasticsearch`?

**Comment by stevehipwell** [comment]
Fixed in PR #4.
