### ISSUE TITLE
Add plugin for geoip

### ISSUE THREAD

**Issue by grioda01** [stevehipwell/fluentd-aggregator#20]
We would like to be able to enrich the logs from our application running on accurnt-dev subscriptions with geo info when collected and parsed by fluentd. Please add fluent-plugin-geoip plugin to the image

**Comment by stevehipwell** [comment]
@grioda01 if the plugin in question is [y-ken/fluent-plugin-geoip](https://github.com/y-ken/fluent-plugin-geoip) then I don't think it's a good fit for this image. I'm not sure that geoip lookup is a core aggregation function and there is complexity involved with integrating this plugin; I'm also not sold on adding plugins with paid for functionality.

**Comment by stevehipwell** [comment]
@grioda01 I think we could re-open this issue and look at the [Banzai Cloud implementation](https://github.com/banzaicloud/logging-operator/blob/master/fluentd-image/v1.14/Dockerfile), I'll open a PR to add it so you can give it a test?

**Comment by grioda01** [comment]
Will sure do, thanks, @stevehipwell
