### ISSUE TITLE
Using latest image: Error when loading pod 

### ISSUE THREAD

**Issue by grioda01** [stevehipwell/fluentd-aggregator#65]
I tried to use your latest image in one of our aks and I noticed the fluentd pods where crashing. Here is the error given in the pod's log

/usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/config/yaml_parser/loader.rb:58:in `initialize': No such file or directory @ rb_sysopen - /fluentd/etc/fluent.yaml (Errno::ENOENT)
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/config/yaml_parser/loader.rb:58:in `open'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/config/yaml_parser/loader.rb:58:in `open'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/config/yaml_parser/loader.rb:58:in `load'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/config/yaml_parser.rb:51:in `parse'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/config.rb:38:in `build'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:810:in `configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:349:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'
        from /usr/bin/fluentd:25:in `load'
        from /usr/bin/fluentd:25:in `<main>'

**Comment by stevehipwell** [comment]
@grioda01 the v2 image isn't compatible with the v1 image or the v2 chart without additional customisation. Based on the error it looks like you haven't overridden the `FLUENTD_CONFIG` env variable.

**Comment by grioda01** [comment]
@stevehipwell , indeed I didn't. 
You did mentioned on another convo about this incompatibility.
Is this ENV variable being set somewhere in the https://github.com/LexisNexis-RBA/terraform-azurerm-aks module?
I can only access the fluentd-aggregator helm through there.

**Comment by grioda01** [comment]
I found where to add the ENV variable for the fluentd pod. It's in core_services_config.fluentd.additional_env
I can only think that by  FLUENTD_CONFIG, you meant FLUENTD_CONF. Which is where fluentd is looking for the conf file base name. I noticed that in v2 Dockerfile you are setting it with the value "fluent.yaml". Then I noticed that you actually are using the 2.7.1 helm chart in the last O.M. release (beta26), rather than the last one, which in turns uses the fluentd-aggregator image tag 1.14.10. 
There the FLUENTD_CONF is set to "fluent.conf" (which is the file mounted by the helm chart in the pod).  THat explains everything. So you are still using V1 in the current O.M.. I guess you'll switch to v2 in later releases?

**Comment by stevehipwell** [comment]
@grioda01 you're absolutely right, I meant `FLUENTD_CONF` but was working from memory without the source code in front of me. We're in the middle of prepping the AKS/EKS modules to support the new image (v2) and chart (v3) by deprecating the old module inputs in favour of a more structured configuration with less potential for misconfiguration. If you DM me on Teams I can give you the relevant links to track when this is due to be released.
